import environ

env = environ.Env()
environ.Env.read_env()

PALAWAN_RECIPIENT = env('PALAWAN_RECIPIENT')
GCASH_NUMBER = env("GCASH_NUMBER")
BDO_ACCOUNT_NUMBER = env('BDO_ACCOUNT_NUMBER')
PSBANK_ACCOUNT_NUMBER = env('PSBANK_ACCOUNT_NUMBER')
SERVICE_ACCOUNT_FILENAME = env("SERVICE_ACCOUNT_FILENAME", default="service_account.json")

# LBC
LBC_API_KEY = env('LBC_API_KEY')
LBC_API_URL = env('LBC_API_URL')
