# Generated by Django 3.2.3 on 2021-05-17 11:13

import clothing_collections.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('for_bid', models.BooleanField(default=True)),
                ('min_bid_add_on', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('shortcut', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to=clothing_collections.models.item_image_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_collections.batch')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing_collections.size')),
            ],
        ),
    ]
