# Generated by Django 3.2.3 on 2021-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'batch', 'verbose_name_plural': 'batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
