# Generated by Django 3.2.4 on 2021-06-28 12:45

import clothing_collections.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_collections', '0003_alter_batch_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='prefix',
            field=models.SlugField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='brand_new',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clothing_collections.models.raw_item_image_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='clothing_collections.batch')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='raw_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clothing_collections.rawitem'),
            preserve_default=False,
        ),
    ]
